# Generated by Django 3.0 on 2020-02-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, max_length=200)),
                ('password', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
