# Generated by Django 3.0 on 2020-02-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20200216_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_1',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_1_grade',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_1_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_2_grade',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_2_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_3',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_3_grade',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_3_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_4',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_4_grade',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_4_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_5',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_5_grade',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_5_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_6',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_6_grade',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_6_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_7',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_7_grade',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_7_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_8',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_8_grade',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='term1_subject_8_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
