# Generated by Django 3.0 on 2020-03-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_auto_20200324_1753'),
        ('lists', '0007_auto_20200324_2026'),
    ]

    operations = [
    ]
