# Generated by Django 3.0 on 2020-04-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_auto_20200501_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('Grade', models.CharField(max_length=255)),
                ('GPA', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Term3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('Grade', models.CharField(max_length=255)),
                ('GPA', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Term4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('Grade', models.CharField(max_length=255)),
                ('GPA', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Term5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('Grade', models.CharField(max_length=255)),
                ('GPA', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Term6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('Grade', models.CharField(max_length=255)),
                ('GPA', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Term7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('Grade', models.CharField(max_length=255)),
                ('GPA', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Term8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('Grade', models.CharField(max_length=255)),
                ('GPA', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Term',
            new_name='Term1',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='term_all',
            new_name='term1',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='term2',
            field=models.ManyToManyField(to='lists.Term2'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='term3',
            field=models.ManyToManyField(to='lists.Term3'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='term4',
            field=models.ManyToManyField(to='lists.Term4'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='term5',
            field=models.ManyToManyField(to='lists.Term5'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='term6',
            field=models.ManyToManyField(to='lists.Term6'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='term7',
            field=models.ManyToManyField(to='lists.Term7'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='term8',
            field=models.ManyToManyField(to='lists.Term8'),
        ),
    ]
