# Generated by Django 3.0 on 2020-04-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_auto_20200501_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('Grade', models.CharField(max_length=255)),
                ('GPA', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='term_All',
            field=models.ManyToManyField(to='lists.Term'),
        ),
    ]
