# Generated by Django 3.0 on 2020-04-30 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0011_auto_20200501_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='term1',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='term2',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='term3',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='term4',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='term5',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='term6',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='term7',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='term8',
        ),
        migrations.DeleteModel(
            name='Term1',
        ),
        migrations.DeleteModel(
            name='Term2',
        ),
        migrations.DeleteModel(
            name='Term3',
        ),
        migrations.DeleteModel(
            name='Term4',
        ),
        migrations.DeleteModel(
            name='Term5',
        ),
        migrations.DeleteModel(
            name='Term6',
        ),
        migrations.DeleteModel(
            name='Term7',
        ),
        migrations.DeleteModel(
            name='Term8',
        ),
    ]
